from workflow.job import Job
from workflow.status import Status
from workflow.process import Process



job = Job(id=1, name="test", process_list=["Process-A", "Process-B", "Process-C"])

print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
job.start()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.put_on_hold()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.resume()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
job.update_job()
print(job.processes[0].name, job.processes[0].status)
print(job.processes[1].name, job.processes[1].status)
print(job.processes[2].name, job.processes[2].status)
print("********JSON Representation**********")
job_string = job.to_json()
print(job_string)
print(type(job_string))
print("********Parse JSON**********")
job = Job.parse(job_string)
print(type(job))
print(job.to_json())
